# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            SAM_STACK_NAME: bananas-service
            SAM_REGION: ca-central-1
            SAM_CAPABILITIES: CAPABILITY_IAM
        steps:
            # - name: Update apt package index and upgrade packages
            #   run: |
            #       sudo apt-get update
            #       sudo apt-get upgrade -y
            #   continue-on-error: true

            # - uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: '1.x'

            - name: Build
              run: go build -o main -ldflags "-linkmode external -extldflags -static" ./...

            # - name: Test
            #   run: go test -v ./...

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ env.SAM_REGION }}

            - name: Deploy with SAM
              run: |
                  sam deploy --stack-name ${{ env.SAM_STACK_NAME }} --region ${{ env.SAM_REGION }} --capabilities ${{ env.SAM_CAPABILITIES }} --resolve-s3 --no-confirm-changeset --no-fail-on-empty-changeset
